[Settings]
ID = "ec2edeb2-c6c9-4fc6-a8f8-a538b4d5ef7a"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.

[build]
  # This is the directory to change to before starting a build.
  base    = "jor-life/"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "jor-life/build/"
  # This will be your default build command
  command = "yarn build"